#!/bin/bash

# Setup zoxide needs to be done before the aliases
eval "$(zoxide init bash)"

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

if [ -f ~/.bash_proxy ]; then
  . ~/.bash_proxy
fi

if [ -f ~/.bash_prompt ]; then
  . ~/.bash_prompt
fi

if [ -f ~/.bash_specific ]; then
  . ~/.bash_specific
fi

# User specific environment
PATH="$HOME/.local/bin:$PATH"

export PATH
