# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Aliases 
alias vi="nvim";
alias vim="nvim";
alias cd="z";
alias cat="bat";
alias ll="ls -al";
alias set_env=". .venv/bin/activate";
alias pbox = "boxes -s 74x1 -a c";






