SPACESHIP_PROMPT_SEPARATE_LINE=false

# User section
SPACESHIP_USER_SHOW=true

# The char before a prompt
SPACESHIP_CHAR_SUFFIX=" "

# Directory section
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_SUFFIX=" "

# GIT section
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_STATUS_SHOW=false
SPACESHIP_GIT_ORDER=(
  git_branch
)

SPACESHIP_CHAR_SHOW=true


SPACESHIP_PROMPT_ORDER=(
  git            
  dir           
  char
)


