#!/bin/bash

# Setup zoxide needs to be done before the aliases
eval "$(zoxide init bash)"

if [ -f "$HOME/.bash_aliases" ]; then
  . "$HOME/.bash_aliases"
fi

if [ -f "$HOME/.bash_proxy" ]; then
  . "$HOME/.bash_proxy"
fi

if [ -f "$HOME/.bash_prompt" ]; then
  . "$HOME/.bash_prompt"
fi

if [ -f "$HOME/.bash_specific" ]; then
  . "$HOME/.bash_specific"
fi

# User specific environment
PATH="./node_modules/.bin:$HOME/.local/bin:$PATH"

export PATH
