#!/bin/bash

if [ -f "$HOME/.bash_prompt" ]; then
  . "$HOME/.bash_prompt"
fi

# Setup zoxide needs to be after the prompt command
# This is because the eval will update the prompt command and add a zoxide hook
# in front of it that is responsible for storing the visited paths
eval "$(zoxide init bash)"

eval "$(fzf --bash)"

if [ -f "$HOME/.bash_aliases" ]; then
  . "$HOME/.bash_aliases"
fi

if [ -f "$HOME/.bash_proxy" ]; then
  . "$HOME/.bash_proxy"
fi

if [ -f "$HOME/.bash_specific" ]; then
  . "$HOME/.bash_specific"
fi

# GIT autocompletion for branches
if [ -f "/usr/share/bash-completion/completions/git" ]; then
  . "/usr/share/bash-completion/completions/git"
fi

# User specific environment
PATH="./node_modules/.bin:$HOME/.local/bin:$PATH"
